Grept apply 1709887482
Azure/terraform-azurerm-avm-res-network-virtualnetwork pull request #54
Opened 2024-03-10 04:39 UTC by herms14

2024-03-10 06:04 UTC, herms14 commented
@Azure/avm-core-team for your review and approval

2024-03-11 19:27 UTC, matt-FFFFFF commented on variables.tf
> +variable "vnet_location" {
variables pertaining the the primary resource, in this case the virtual network, should not be prefixed

2024-03-11 19:28 UTC, matt-FFFFFF requested changes
Hey! this is fantastic work, couple of comments on variable naming

2024-03-11 19:28 UTC, matt-FFFFFF commented on variables.tf
> +variable "vnet_name" {
See above shoudl call this `name`

2024-03-17 10:16 UTC, herms14 commented
Thanks for the review @matt-FFFFFF. Names has been updated now.

2024-03-20 08:23 UTC, matt-FFFFFF approved these changes

2024-03-20 08:24 UTC, merged